# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.srcs/sources_1/bd/driverSystem/ip/driverSystem_axi_smc_0/driverSystem_axi_smc_0.xci
# IP: The module: 'driverSystem_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.gen/sources_1/bd/driverSystem/ip/driverSystem_axi_smc_0/bd_0/bd_8f8c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.gen/sources_1/bd/driverSystem/ip/driverSystem_axi_smc_0/bd_0/ip/ip_0/bd_8f8c_sc_ul_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.gen/sources_1/bd/driverSystem/ip/driverSystem_axi_smc_0/bd_0/ip/ip_0/bd_8f8c_sc_ul_0_cdc.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.gen/sources_1/bd/driverSystem/ip/driverSystem_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'driverSystem_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.gen/sources_1/bd/driverSystem/ip/driverSystem_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'driverSystem_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.srcs/sources_1/bd/driverSystem/ip/driverSystem_axi_smc_0/driverSystem_axi_smc_0.xci
# IP: The module: 'driverSystem_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.gen/sources_1/bd/driverSystem/ip/driverSystem_axi_smc_0/bd_0/bd_8f8c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.gen/sources_1/bd/driverSystem/ip/driverSystem_axi_smc_0/bd_0/ip/ip_0/bd_8f8c_sc_ul_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.gen/sources_1/bd/driverSystem/ip/driverSystem_axi_smc_0/bd_0/ip/ip_0/bd_8f8c_sc_ul_0_cdc.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.gen/sources_1/bd/driverSystem/ip/driverSystem_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'driverSystem_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.gen/sources_1/bd/driverSystem/ip/driverSystem_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'driverSystem_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
