# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Spartan7/Arty-S7-25-Master.xdc

# Block Designs: bd/driverSystem/driverSystem.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem || ORIG_REF_NAME==driverSystem} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_rst_clk_wiz_1_100M_0/driverSystem_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==driverSystem_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_axi_quad_spi_0_0/driverSystem_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_axi_quad_spi_0_0 || ORIG_REF_NAME==driverSystem_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_microblaze_0_0/driverSystem_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_microblaze_0_0 || ORIG_REF_NAME==driverSystem_microblaze_0_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_axi_gpio_0_0/driverSystem_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_axi_gpio_0_0 || ORIG_REF_NAME==driverSystem_axi_gpio_0_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_mdm_1_0/driverSystem_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_mdm_1_0 || ORIG_REF_NAME==driverSystem_mdm_1_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_axi_smc_0/driverSystem_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_axi_smc_0 || ORIG_REF_NAME==driverSystem_axi_smc_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_clk_wiz_1_0/driverSystem_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_clk_wiz_1_0 || ORIG_REF_NAME==driverSystem_clk_wiz_1_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_dlmb_v10_0/driverSystem_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_dlmb_v10_0 || ORIG_REF_NAME==driverSystem_dlmb_v10_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_ilmb_v10_0/driverSystem_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_ilmb_v10_0 || ORIG_REF_NAME==driverSystem_ilmb_v10_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_dlmb_bram_if_cntlr_0/driverSystem_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==driverSystem_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_ilmb_bram_if_cntlr_0/driverSystem_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==driverSystem_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_lmb_bram_0/driverSystem_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_lmb_bram_0 || ORIG_REF_NAME==driverSystem_lmb_bram_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_xlslice_0_0/driverSystem_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_xlslice_0_0 || ORIG_REF_NAME==driverSystem_xlslice_0_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_xlslice_1_1/driverSystem_xlslice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_xlslice_1_1 || ORIG_REF_NAME==driverSystem_xlslice_1_1} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_axi_uartlite_0_0/driverSystem_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_axi_uartlite_0_0 || ORIG_REF_NAME==driverSystem_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_xlslice_2_0/driverSystem_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_xlslice_2_0 || ORIG_REF_NAME==driverSystem_xlslice_2_0} -quiet] -quiet

# IP: bd/driverSystem/ip/driverSystem_bnn_axi_0_2/driverSystem_bnn_axi_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==driverSystem_bnn_axi_0_2 || ORIG_REF_NAME==driverSystem_bnn_axi_0_2} -quiet] -quiet

# XDC: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.gen/sources_1/bd/driverSystem/driverSystem_ooc.xdc
