# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.srcs/sources_1/bd/driverSystem/ip/driverSystem_dlmb_v10_0/driverSystem_dlmb_v10_0.xci
# IP: The module: 'driverSystem_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.gen/sources_1/bd/driverSystem/ip/driverSystem_dlmb_v10_0/driverSystem_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'driverSystem_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.srcs/sources_1/bd/driverSystem/ip/driverSystem_dlmb_v10_0/driverSystem_dlmb_v10_0.xci
# IP: The module: 'driverSystem_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/AmbitiousProjects/ILI9341Driver/driverSoC/driverSoC.gen/sources_1/bd/driverSystem/ip/driverSystem_dlmb_v10_0/driverSystem_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'driverSystem_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
